apiVersion: v1
kind: Pod
metadata:
 name: web-first
 labels:
  app: nginx
spec:
 containers:
 - name: nginx
   image: nginx:latest
   ports:
   - containerPort: 8090
 imagePullSecrets:
 - name : jarrod-secret-test
